In [90]:
import pandas as pd
import os

print(os.getcwd())
df = pd.read_csv(
    "../data/ai_job_impact_dataset.csv"
)

print(df.head())

/Users/syedafnan/First Semester/Statistics & ML/impact-ai-jobs-impact-ml/notebooks
   worker_id     country      continent  year   age  gender education_level  \
0          1  Bangladesh           Asia  2035  36.0    Male        Bachelor
1          2     Denmark         Europe  2035  58.0    Male        Bachelor
2          3     Nigeria         Africa  2035  59.0  Female     High School
3          4     Vietnam           Asia  2035  54.0  Female        Bachelor
4          5      Mexico  North America  2034  54.0  Female        Bachelor

         industry               job_role  years_experience  ...  \
0          Energy         Energy Auditor               7.0  ...
1  Transportation      Aviation Mechanic              13.0  ...
2              IT        DevOps Engineer              34.0  ...
3   Manufacturing  Production Supervisor              21.0  ...
4          Retail      Inventory Manager              13.0  ...

   training_hours reskilling_completed automation_probability  \
0           136.0                   No                 0.4382
1            55.5                  Yes                 0.4848
2           110.8                   No                 0.4564
3           109.7                  Yes                 0.6871
4            71.3                  Yes                 0.3714

  job_satisfaction  promotion_probability  layoff_probability  \
0             8.01                 0.5516              0.1362
1             8.00                 0.4824              0.2122
2             6.11                 0.3561              0.1431
3             5.64                 0.3547              0.2724
4             9.68                 0.4796              0.1333

   employment_status_after_ai  annual_performance_rating  mental_stress_score  \
0                    Employed                       4.16                23.29
1                    Employed                       3.65                19.45
2                    Employed                       3.42                47.87
3                    Employed                       3.77                38.92
4                    Employed                       3.79                27.33

   innovation_score
0             46.19
1             59.25
2             16.69
3             39.84
4             47.53

[5 rows x 29 columns]

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 29 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   worker_id                   100000 non-null  int64
 1   country                     100000 non-null  object
 2   continent                   97908 non-null   object
 3   year                        100000 non-null  int64
 4   age                         97973 non-null   float64
 5   gender                      97996 non-null   object
 6   education_level             97999 non-null   object
 7   industry                    98006 non-null   object
 8   job_role                    97949 non-null   object
 9   years_experience            97977 non-null   float64
 10  salary_usd                  97965 non-null   float64
 11  employment_type             97983 non-null   object
 12  company_size                98012 non-null   object
 13  remote_work                 98074 non-null   object
 14  ai_adoption_level           97998 non-null   float64
 15  ai_literacy_score           97989 non-null   float64
 16  digital_skill_score         98106 non-null   float64
 17  productivity_score          97965 non-null   float64
 18  hours_worked_per_week       97964 non-null   float64
 19  training_hours              98068 non-null   float64
 20  reskilling_completed        97971 non-null   object
 21  automation_probability      98042 non-null   float64
 22  job_satisfaction            98052 non-null   float64
 23  promotion_probability       98025 non-null   float64
 24  layoff_probability          98036 non-null   float64
 25  employment_status_after_ai  97993 non-null   object
 26  annual_performance_rating   98059 non-null   float64
 27  mental_stress_score         97990 non-null   float64
 28  innovation_score            97999 non-null   float64
dtypes: float64(16), int64(2), object(11)
memory usage: 22.1+ MB

In [92]:
df.describe()

,worker_id,year,age,years_experience,salary_usd,ai_adoption_level,ai_literacy_score,digital_skill_score,productivity_score,hours_worked_per_week,training_hours,automation_probability,job_satisfaction,promotion_probability,layoff_probability,annual_performance_rating,mental_stress_score,innovation_score
count,100000.000000,100000.000000,97973.000000,97977.000000,97965.000000,97998.000000,97989.000000,98106.000000,97965.000000,97964.000000,98068.000000,98042.000000,98052.000000,98025.000000,98036.000000,98059.000000,97990.000000,97999.000000
mean,50003.747580,2027.486270,41.450655,10.348714,53476.163239,71.926492,45.663136,37.567071,52.064336,39.889859,80.504905,0.369497,7.114112,0.426237,0.133217,3.081087,28.728079,45.115835
std,28859.224175,4.605022,13.868108,8.886407,53896.939841,21.098684,21.016159,18.539245,16.141847,8.871282,30.737865,0.123245,1.141833,0.102881,0.106129,0.863304,9.753149,20.599814
min,1.000000,2020.000000,18.000000,0.000000,1500.000000,0.000000,0.000000,0.000000,0.000000,8.000000,0.000000,0.000000,2.430000,0.040000,0.000000,1.000000,0.000000,0.000000
25%,25029.750000,2023.000000,29.000000,3.000000,13543.990000,56.890000,29.110000,23.750000,40.910000,36.100000,58.600000,0.286700,6.340000,0.355100,0.040475,2.490000,22.030000,30.300000
50%,49985.500000,2027.000000,41.000000,8.000000,32782.070000,73.140000,45.210000,37.090000,51.870000,41.700000,80.900000,0.370000,7.120000,0.425300,0.123400,3.080000,28.560000,44.520000
75%,74994.250000,2031.000000,53.000000,16.000000,77536.110000,90.120000,61.420000,50.810000,63.190000,45.900000,102.800000,0.448700,7.890000,0.496800,0.206200,3.680000,35.260000,59.200000
max,100000.000000,2035.000000,65.000000,46.000000,497176.080000,100.000000,100.000000,100.000000,100.000000,64.100000,190.100000,0.860300,10.000000,0.827300,0.619100,5.000000,76.880000,100.000000

In [93]:
df.shape

(100000, 29)

In [94]:
df.columns

Index(['worker_id', 'country', 'continent', 'year', 'age', 'gender',
       'education_level', 'industry', 'job_role', 'years_experience',
       'salary_usd', 'employment_type', 'company_size', 'remote_work',
       'ai_adoption_level', 'ai_literacy_score', 'digital_skill_score',
       'productivity_score', 'hours_worked_per_week', 'training_hours',
       'reskilling_completed', 'automation_probability', 'job_satisfaction',
       'promotion_probability', 'layoff_probability',
       'employment_status_after_ai', 'annual_performance_rating',
       'mental_stress_score', 'innovation_score'],
      dtype='object')

In [95]:
df.isnull().sum()

worker_id                        0
country                          0
continent                     2092
year                             0
age                           2027
gender                        2004
education_level               2001
industry                      1994
job_role                      2051
years_experience              2023
salary_usd                    2035
employment_type               2017
company_size                  1988
remote_work                   1926
ai_adoption_level             2002
ai_literacy_score             2011
digital_skill_score           1894
productivity_score            2035
hours_worked_per_week         2036
training_hours                1932
reskilling_completed          2029
automation_probability        1958
job_satisfaction              1948
promotion_probability         1975
layoff_probability            1964
employment_status_after_ai    2007
annual_performance_rating     1941
mental_stress_score           2010
innovation_score              2001
dtype: int64

In [96]:
df["employment_status_after_ai"].value_counts()

employment_status_after_ai
Employed         85571
Reskilled         7430
Career Change     3685
Unemployed        1307
Name: count, dtype: int64

In [97]:
df["employment_status_after_ai"].unique()

array(['Employed', 'Reskilled', 'Career Change', 'Unemployed', nan],
      dtype=object)

In [98]:
df.isnull().sum().sort_values(ascending=False)

continent                     2092
job_role                      2051
hours_worked_per_week         2036
salary_usd                    2035
productivity_score            2035
reskilling_completed          2029
age                           2027
years_experience              2023
employment_type               2017
ai_literacy_score             2011
mental_stress_score           2010
employment_status_after_ai    2007
gender                        2004
ai_adoption_level             2002
innovation_score              2001
education_level               2001
industry                      1994
company_size                  1988
promotion_probability         1975
layoff_probability            1964
automation_probability        1958
job_satisfaction              1948
annual_performance_rating     1941
training_hours                1932
remote_work                   1926
digital_skill_score           1894
country                          0
year                             0
worker_id                        0
dtype: int64

In [99]:
df = df.dropna(subset=["employment_status_after_ai"])

In [100]:
df["employment_status_after_ai"].isnull().sum()

np.int64(0)

In [101]:
df.shape

(97993, 29)

In [102]:
X = df.drop(columns=["employment_status_after_ai"])

y = df["employment_status_after_ai"]

In [103]:
print(X.shape)
print(y.shape)

(97993, 28)
(97993,)

In [104]:
categorical_cols = X.select_dtypes(include=["object"]).columns

numerical_cols = X.select_dtypes(include=["int64", "float64"]).columns

print("Categorical columns:")
print(categorical_cols)

print("\nNumerical columns:")
print(numerical_cols)

Categorical columns:
Index(['country', 'continent', 'gender', 'education_level', 'industry',
       'job_role', 'employment_type', 'company_size', 'remote_work',
       'reskilling_completed'],
      dtype='object')

Numerical columns:
Index(['worker_id', 'year', 'age', 'years_experience', 'salary_usd',
       'ai_adoption_level', 'ai_literacy_score', 'digital_skill_score',
       'productivity_score', 'hours_worked_per_week', 'training_hours',
       'automation_probability', 'job_satisfaction', 'promotion_probability',
       'layoff_probability', 'annual_performance_rating',
       'mental_stress_score', 'innovation_score'],
      dtype='object')

In [105]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)
# Using stratify=y ensures the train and test sets keep approximately the same class proportions.

In [106]:
print(X_train.shape)
print(X_test.shape)

(78394, 28)
(19599, 28)

In [107]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

In [108]:
numeric_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median"))
    ]
)

In [109]:
categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ]
)

In [110]:
handle_unknown="ignore"

In [112]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numerical_cols),
        ("cat", categorical_transformer, categorical_cols)
    ]
)

In [113]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  Index(['worker_id', 'year', 'age', 'years_experience', 'salary_usd',
       'ai_adoption_level', 'ai_literacy_score', 'digital_skill_score',
       'productivity_score', 'hours_worked_per_week', 'training_hours',
       'automation_probability', 'jo...
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['country', 'continent', 'gender', 'education_level', 'industry',
       'job_role', 'employment_type', 'company_size', 'remote_work',
       'reskilling_completed'],
      dtype='object'))])),
                ('classifier',
                 RandomForestClassifier(class_weight='balanced',
                                        random_state=42))])

In [114]:
from sklearn.ensemble import RandomForestClassifier

In [117]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", RandomForestClassifier(random_state=42))
    ]
)

In [118]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  Index(['worker_id', 'year', 'age', 'years_experience', 'salary_usd',
       'ai_adoption_level', 'ai_literacy_score', 'digital_skill_score',
       'productivity_score', 'hours_worked_per_week', 'training_hours',
       'automation_probability', 'jo...
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['country', 'continent', 'gender', 'education_level', 'industry',
       'job_role', 'employment_type', 'company_size', 'remote_work',
       'reskilling_completed'],
      dtype='object'))])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [119]:
y_pred = pipeline.predict(X_test)

In [120]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.8754528292259809

In [121]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

               precision    recall  f1-score   support

Career Change       0.52      0.02      0.04       737
     Employed       0.88      1.00      0.93     17115
    Reskilled       0.83      0.01      0.02      1486
   Unemployed       0.52      0.13      0.20       261

     accuracy                           0.88     19599
    macro avg       0.69      0.29      0.30     19599
 weighted avg       0.86      0.88      0.82     19599

This output is actually very informative. Your model is not performing as well as the accuracy suggests.

Your accuracy:

0.88 (88%)

looks good at first, but the classification report shows a problem.

In [122]:
pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", RandomForestClassifier(
            random_state=42,
            class_weight="balanced"
        ))
    ]
)

In [123]:
pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_test)

In [124]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

               precision    recall  f1-score   support

Career Change       0.29      0.09      0.13       737
     Employed       0.89      0.99      0.94     17115
    Reskilled       0.34      0.03      0.06      1486
   Unemployed       0.47      0.64      0.54       261

     accuracy                           0.87     19599
    macro avg       0.50      0.44      0.42     19599
 weighted avg       0.82      0.87      0.84     19599

In [125]:
from sklearn.linear_model import LogisticRegression

In [126]:
lr_model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=42
)

In [127]:
lr_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", lr_model)
    ]
)

In [128]:
lr_pipeline.fit(X_train, y_train)

/Users/syedafnan/First Semester/Statistics & ML/impact-ai-jobs-impact-ml/ml_venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  Index(['worker_id', 'year', 'age', 'years_experience', 'salary_usd',
       'ai_adoption_level', 'ai_literacy_score', 'digital_skill_score',
       'productivity_score', 'hours_worked_per_week', 'training_hours',
       'automation_probability', 'jo...
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['country', 'continent', 'gender', 'education_level', 'industry',
       'job_role', 'employment_type', 'company_size', 'remote_work',
       'reskilling_completed'],
      dtype='object'))])),
                ('classifier',
                 LogisticRegression(class_weight='balanced', max_iter=1000,
                                    random_state=42))])

In [129]:
lr_pred = lr_pipeline.predict(X_test)

In [130]:
print(classification_report(y_test, lr_pred))

               precision    recall  f1-score   support

Career Change       0.06      0.24      0.10       737
     Employed       0.92      0.56      0.70     17115
    Reskilled       0.08      0.17      0.11      1486
   Unemployed       0.05      0.62      0.10       261

     accuracy                           0.52     19599
    macro avg       0.28      0.40      0.25     19599
 weighted avg       0.81      0.52      0.62     19599

In [131]:
from xgboost import XGBClassifier

In [132]:
xgb_model = XGBClassifier(
    n_estimators=200,
    learning_rate=0.1,
    random_state=42
)

In [133]:
xgb_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", xgb_model)
    ]
)

In [135]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

In [136]:
print(y_train_encoded[:100])

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 3 1 1 1 1 1 1 0
 2 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 2 1
 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 0 1 2 1 1 2 1 1 1 1 1]

In [137]:
print(label_encoder.classes_)

['Career Change' 'Employed' 'Reskilled' 'Unemployed']

In [138]:
xgb_pipeline.fit(X_train, y_train_encoded)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  Index(['worker_id', 'year', 'age', 'years_experience', 'salary_usd',
       'ai_adoption_level', 'ai_literacy_score', 'digital_skill_score',
       'productivity_score', 'hours_worked_per_week', 'training_hours',
       'automation_probability', 'jo...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.1,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=200, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [139]:
xgb_pred = xgb_pipeline.predict(X_test)

In [140]:
print(xgb_pred)

[1 1 1 ... 1 1 1]

In [142]:
xgb_pred_labels = label_encoder.inverse_transform(xgb_pred)
print(xgb_pred_labels)

['Employed' 'Employed' 'Employed' ... 'Employed' 'Employed' 'Employed']

In [144]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test_encoded,
        xgb_pred
    )
)

              precision    recall  f1-score   support

           0       0.29      0.04      0.08       737
           1       0.89      0.99      0.94     17115
           2       0.49      0.01      0.02      1486
           3       0.47      0.67      0.55       261

    accuracy                           0.88     19599
   macro avg       0.53      0.43      0.40     19599
weighted avg       0.83      0.88      0.83     19599

In [146]:
from sklearn.metrics import f1_score, accuracy_score

models = {
    "Random Forest": y_pred,
    "Logistic Regression": lr_pred,
    "XGBoost": xgb_pred_labels
}

for name, pred in models.items():
    print(name)
    print("Accuracy:", accuracy_score(y_test, pred))
    print("Macro F1:", f1_score(y_test, pred, average="macro"))
    print("----------------")

Random Forest
Accuracy: 0.8748405530894433
Macro F1: 0.4197011461705493
----------------
Logistic Regression
Accuracy: 0.5216592683300169
Macro F1: 0.25025700396641154
----------------
XGBoost
Accuracy: 0.8784121638859126
Macro F1: 0.3981690565068611
----------------

feature analysis and selection.

In [148]:
import pandas as pd

importance = pd.DataFrame({
    "feature": X_train.columns,
    "importance": y_pred.feature_importances_
})

importance = importance.sort_values(
    by="importance",
    ascending=False
)

importance

AttributeError: 'numpy.ndarray' object has no attribute 'feature_importances_'

In [150]:
rf_model = pipeline.named_steps["classifier"]

In [151]:
feature_names = pipeline.named_steps["preprocessor"].get_feature_names_out()

In [250]:
import pandas as pd

importance = pd.DataFrame({
    "feature": feature_names,
    "importance": rf_model.feature_importances_
})

importance = importance.sort_values(
    by="importance",
    ascending=False
)

importance.head(28)

                            feature  importance
14          num__layoff_probability    0.175636
11      num__automation_probability    0.047842
16         num__mental_stress_score    0.046685
12            num__job_satisfaction    0.030372
10              num__training_hours    0.030278
6            num__ai_literacy_score    0.029876
17            num__innovation_score    0.029488
7          num__digital_skill_score    0.029308
8           num__productivity_score    0.029148
4                   num__salary_usd    0.028919
13       num__promotion_probability    0.028723
0                    num__worker_id    0.028257
15   num__annual_performance_rating    0.027929
9        num__hours_worked_per_week    0.027597
5            num__ai_adoption_level    0.026448
2                          num__age    0.025005
3             num__years_experience    0.022765
1                         num__year    0.021664
407    cat__reskilling_completed_No    0.013002
408   cat__reskilling_completed_Yes    0.012863
404         cat__company_size_Small    0.011253
94      cat__industry_Manufacturing    0.009593
401    cat__company_size_Enterprise    0.006487
76               cat__gender_Female    0.005882
77                 cat__gender_Male    0.005748
71              cat__continent_Asia    0.005566
399  cat__employment_type_Full-time    0.005052
402         cat__company_size_Large    0.004935

Next Phase

In [154]:
features = [
    "country",
    "industry",
    "education_level",
    "job_role",
    "years_experience",
    "salary_usd",
    "company_size",
    "remote_work",
    "ai_adoption_level",
    "ai_literacy_score",
    "training_hours",
    "reskilling_completed",
    "automation_probability",
    "layoff_probability"
]

target = "employment_status_after_ai"

In [155]:
X = df[features]
y = df[target]

In [ ]:
print(X.shape)
print(y.shape)

(97993, 14)
(97993,)
<bound method NDFrame.head of 0             Employed
1             Employed
2             Employed
3             Employed
4             Employed
             ...
99995         Employed
99996    Career Change
99997         Employed
99998         Employed
99999        Reskilled
Name: employment_status_after_ai, Length: 97993, dtype: object>

In [160]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 97993 entries, 0 to 99999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 97993 non-null  object
 1   industry                96042 non-null  object
 2   education_level         96026 non-null  object
 3   job_role                95986 non-null  object
 4   years_experience        96019 non-null  float64
 5   salary_usd              96006 non-null  float64
 6   company_size            96040 non-null  object
 7   remote_work             96113 non-null  object
 8   ai_adoption_level       96033 non-null  float64
 9   ai_literacy_score       96026 non-null  float64
 10  training_hours          96096 non-null  float64
 11  reskilling_completed    96003 non-null  object
 12  automation_probability  96080 non-null  float64
 13  layoff_probability      96079 non-null  float64
dtypes: float64(7), object(7)
memory usage: 11.2+ MB

In [162]:
X.isnull().sum()

country                      0
industry                  1951
education_level           1967
job_role                  2007
years_experience          1974
salary_usd                1987
company_size              1953
remote_work               1880
ai_adoption_level         1960
ai_literacy_score         1967
training_hours            1897
reskilling_completed      1990
automation_probability    1913
layoff_probability        1914
dtype: int64

In [165]:
y.info()

<class 'pandas.core.series.Series'>
Index: 97993 entries, 0 to 99999
Series name: employment_status_after_ai
Non-Null Count  Dtype
--------------  -----
97993 non-null  object
dtypes: object(1)
memory usage: 1.5+ MB

In [166]:
df[target].value_counts()

employment_status_after_ai
Employed         85571
Reskilled         7430
Career Change     3685
Unemployed        1307
Name: count, dtype: int64

In [169]:
df[target].isnull().sum()

np.int64(0)

In [170]:
df[target].unique()

array(['Employed', 'Reskilled', 'Career Change', 'Unemployed'],
      dtype=object)

In [171]:
X["industry"].unique()

array(['Energy', 'Transportation', 'IT', 'Manufacturing', 'Retail',
       'Agriculture', 'Education', 'Legal', 'Construction', 'Government',
       'Healthcare', 'Hospitality', 'Finance', nan, 'Media',
       'Telecommunications'], dtype=object)

In [172]:
dir()

['ColumnTransformer',
 'In',
 'LabelEncoder',
 'LogisticRegression',
 'OneHotEncoder',
 'Out',
 'Pipeline',
 'RandomForestClassifier',
 'SimpleImputer',
 'X',
 'XGBClassifier',
 'X_test',
 'X_train',
 '_',
 '_100',
 '_101',
 '_11',
 '_113',
 '_118',
 '_12',
 '_128',
 '_13',
 '_138',
 '_14',
 '_15',
 '_152',
 '_159',
 '_16',
 '_161',
 '_162',
 '_163',
 '_166',
 '_167',
 '_168',
 '_169',
 '_17',
 '_170',
 '_171',
 '_20',
 '_21',
 '_22',
 '_23',
 '_43',
 '_54',
 '_76',
 '_92',
 '_93',
 '_94',
 '_95',
 '_96',
 '_97',
 '_98',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__vsc_ipynb_file__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i100',
 '_i101',
 '_i102',
 '_i103',
 '_i104',
 '_i105',
 '_i106',
 '_i107',
 '_i108',
 '_i109',
 '_i11',
 '_i110',
 '_i111',
 '_i112',
 '_i113',
 '_i114',
 '_i115',
 '_i116',
 '_i117',
 '_i118',
 '_i119',
 '_i12',
 '_i120',
 '_i121',
 '_i122',
 '_i123',
 '_i124',
 '_i125',
 '_i126',
 '_i127',
 '_i128',
 '_i129',
 '_i13',
 '_i130',
 '_i131',
 '_i132',
 '_i133',
 '_i134',
 '_i135',
 '_i136',
 '_i137',
 '_i138',
 '_i139',
 '_i14',
 '_i140',
 '_i141',
 '_i142',
 '_i143',
 '_i144',
 '_i145',
 '_i146',
 '_i147',
 '_i148',
 '_i149',
 '_i15',
 '_i150',
 '_i151',
 '_i152',
 '_i153',
 '_i154',
 '_i155',
 '_i156',
 '_i157',
 '_i158',
 '_i159',
 '_i16',
 '_i160',
 '_i161',
 '_i162',
 '_i163',
 '_i164',
 '_i165',
 '_i166',
 '_i167',
 '_i168',
 '_i169',
 '_i17',
 '_i170',
 '_i171',
 '_i172',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i24',
 '_i25',
 '_i26',
 '_i27',
 '_i28',
 '_i29',
 '_i3',
 '_i30',
 '_i31',
 '_i32',
 '_i33',
 '_i34',
 '_i35',
 '_i36',
 '_i37',
 '_i38',
 '_i39',
 '_i4',
 '_i40',
 '_i41',
 '_i42',
 '_i43',
 '_i44',
 '_i45',
 '_i46',
 '_i47',
 '_i48',
 '_i49',
 '_i5',
 '_i50',
 '_i51',
 '_i52',
 '_i53',
 '_i54',
 '_i55',
 '_i56',
 '_i57',
 '_i58',
 '_i59',
 '_i6',
 '_i60',
 '_i61',
 '_i62',
 '_i63',
 '_i64',
 '_i65',
 '_i66',
 '_i67',
 '_i68',
 '_i69',
 '_i7',
 '_i70',
 '_i71',
 '_i72',
 '_i73',
 '_i74',
 '_i75',
 '_i76',
 '_i77',
 '_i78',
 '_i79',
 '_i8',
 '_i80',
 '_i81',
 '_i82',
 '_i83',
 '_i84',
 '_i85',
 '_i86',
 '_i87',
 '_i88',
 '_i89',
 '_i9',
 '_i90',
 '_i91',
 '_i92',
 '_i93',
 '_i94',
 '_i95',
 '_i96',
 '_i97',
 '_i98',
 '_i99',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'accuracy',
 'accuracy_score',
 'categorical_cols',
 'categorical_transformer',
 'classification_report',
 'df',
 'exit',
 'f1_score',
 'feature_names',
 'features',
 'get_ipython',
 'handle_unknown',
 'importance',
 'label_encoder',
 'lr_model',
 'lr_pipeline',
 'lr_pred',
 'models',
 'name',
 'numeric_transformer',
 'numerical_cols',
 'open',
 'os',
 'pd',
 'pipeline',
 'platform',
 'pred',
 'preprocessor',
 'quit',
 'rf_model',
 'sys',
 'target',
 'train_test_split',
 'xgb_model',
 'xgb_pipeline',
 'xgb_pred',
 'xgb_pred_labels',
 'y',
 'y_pred',
 'y_test',
 'y_test_encoded',
 'y_train',
 'y_train_encoded']

In [175]:
import os

os.getcwd()
os.listdir()

['exploration.ipynb']

In [177]:
import pandas as pd

df = pd.read_csv("../data/ai_job_impact_dataset.csv")

In [178]:
df.head()

,worker_id,country,continent,year,age,gender,education_level,industry,job_role,years_experience,...,training_hours,reskilling_completed,automation_probability,job_satisfaction,promotion_probability,layoff_probability,employment_status_after_ai,annual_performance_rating,mental_stress_score,innovation_score
0,1,Bangladesh,Asia,2035,36.0,Male,Bachelor,Energy,Energy Auditor,7.0,...,136.0,No,0.4382,8.01,0.5516,0.1362,Employed,4.16,23.29,46.19
1,2,Denmark,Europe,2035,58.0,Male,Bachelor,Transportation,Aviation Mechanic,13.0,...,55.5,Yes,0.4848,8.00,0.4824,0.2122,Employed,3.65,19.45,59.25
2,3,Nigeria,Africa,2035,59.0,Female,High School,IT,DevOps Engineer,34.0,...,110.8,No,0.4564,6.11,0.3561,0.1431,Employed,3.42,47.87,16.69
3,4,Vietnam,Asia,2035,54.0,Female,Bachelor,Manufacturing,Production Supervisor,21.0,...,109.7,Yes,0.6871,5.64,0.3547,0.2724,Employed,3.77,38.92,39.84
4,5,Mexico,North America,2034,54.0,Female,Bachelor,Retail,Inventory Manager,13.0,...,71.3,Yes,0.3714,9.68,0.4796,0.1333,Employed,3.79,27.33,47.53

In [179]:
features = [
    "country",
    "industry",
    "education_level",
    "job_role",
    "years_experience",
    "salary_usd",
    "company_size",
    "remote_work",
    "ai_adoption_level",
    "ai_literacy_score",
    "training_hours",
    "reskilling_completed",
    "automation_probability",
    "layoff_probability"
]

target = "employment_status_after_ai"

X = df[features]
y = df[target]

In [180]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   country                 100000 non-null  object
 1   industry                98006 non-null   object
 2   education_level         97999 non-null   object
 3   job_role                97949 non-null   object
 4   years_experience        97977 non-null   float64
 5   salary_usd              97965 non-null   float64
 6   company_size            98012 non-null   object
 7   remote_work             98074 non-null   object
 8   ai_adoption_level       97998 non-null   float64
 9   ai_literacy_score       97989 non-null   float64
 10  training_hours          98068 non-null   float64
 11  reskilling_completed    97971 non-null   object
 12  automation_probability  98042 non-null   float64
 13  layoff_probability      98036 non-null   float64
dtypes: float64(7), object(7)
memory usage: 10.7+ MB

In [182]:
X.isnull().sum()

country                      0
industry                  1994
education_level           2001
job_role                  2051
years_experience          2023
salary_usd                2035
company_size              1988
remote_work               1926
ai_adoption_level         2002
ai_literacy_score         2011
training_hours            1932
reskilling_completed      2029
automation_probability    1958
layoff_probability        1964
dtype: int64

In [183]:
y.isnull().sum()

np.int64(2007)

In [184]:
model_data = pd.concat([X, y], axis=1)

In [185]:
model_data.isnull().sum()

country                          0
industry                      1994
education_level               2001
job_role                      2051
years_experience              2023
salary_usd                    2035
company_size                  1988
remote_work                   1926
ai_adoption_level             2002
ai_literacy_score             2011
training_hours                1932
reskilling_completed          2029
automation_probability        1958
layoff_probability            1964
employment_status_after_ai    2007
dtype: int64

In [186]:
model_data_clean = model_data.dropna()

In [187]:
print("Before:", model_data.shape)

Before: (100000, 15)

In [188]:
print("After:", model_data_clean.shape)

After: (75441, 15)

In [189]:
model_data_clean.isnull().sum()

country                       0
industry                      0
education_level               0
job_role                      0
years_experience              0
salary_usd                    0
company_size                  0
remote_work                   0
ai_adoption_level             0
ai_literacy_score             0
training_hours                0
reskilling_completed          0
automation_probability        0
layoff_probability            0
employment_status_after_ai    0
dtype: int64

In [190]:
X = model_data_clean[features]
y = model_data_clean[target]

In [191]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 75441 entries, 0 to 99999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 75441 non-null  object
 1   industry                75441 non-null  object
 2   education_level         75441 non-null  object
 3   job_role                75441 non-null  object
 4   years_experience        75441 non-null  float64
 5   salary_usd              75441 non-null  float64
 6   company_size            75441 non-null  object
 7   remote_work             75441 non-null  object
 8   ai_adoption_level       75441 non-null  float64
 9   ai_literacy_score       75441 non-null  float64
 10  training_hours          75441 non-null  float64
 11  reskilling_completed    75441 non-null  object
 12  automation_probability  75441 non-null  float64
 13  layoff_probability      75441 non-null  float64
dtypes: float64(7), object(7)
memory usage: 8.6+ MB

In [192]:
y.info()

<class 'pandas.core.series.Series'>
Index: 75441 entries, 0 to 99999
Series name: employment_status_after_ai
Non-Null Count  Dtype
--------------  -----
75441 non-null  object
dtypes: object(1)
memory usage: 1.2+ MB

In [196]:
model_data_clean[model_data_clean.duplicated()]

,country,industry,education_level,job_role,years_experience,salary_usd,company_size,remote_work,ai_adoption_level,ai_literacy_score,training_hours,reskilling_completed,automation_probability,layoff_probability,employment_status_after_ai
1364,USA,Education,Diploma,Teacher,12.0,56659.01,Small,No,27.18,35.95,30.0,No,0.1437,0.1486,Employed
1998,Greece,Media,High School,Editor,9.0,42297.53,Enterprise,No,100.00,38.27,108.8,Yes,0.5919,0.0429,Employed
6138,Peru,Government,Bachelor,Regulatory Officer,13.0,24632.97,Enterprise,Yes,68.64,53.52,117.6,No,0.3293,0.0074,Employed
6462,Spain,Construction,PhD,Crane Operator,3.0,60431.65,Medium,Yes,65.80,82.22,75.5,No,0.4164,0.2833,Employed
6546,USA,Legal,PhD,Prosecutor,0.0,162000.21,Medium,No,64.03,74.55,82.9,Yes,0.2335,0.0000,Employed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99137,UK,Retail,Master,Pricing Analyst,25.0,104495.29,Large,No,57.12,69.77,91.1,No,0.4900,0.2165,Career Change
99163,Canada,Legal,Master,Lawyer,8.0,208357.69,Enterprise,No,81.23,68.08,78.0,No,0.1728,0.1212,Employed
99235,Argentina,IT,Bachelor,Network Engineer,2.0,45928.33,Medium,Yes,100.00,79.25,100.2,Yes,0.1834,0.0859,Employed
99666,Malaysia,Media,Bachelor,News Anchor,2.0,40126.74,Large,No,65.50,71.31,55.5,No,0.2498,0.0579,Employed
99894,Nigeria,Energy,Diploma,Utility Manager,4.0,12888.96,Enterprise,Yes,100.00,37.43,130.5,No,0.5090,0.1018,Employed

In [207]:
model_data_clean.duplicated().sum()

np.int64(382)

In [204]:
75441 - 382

75059

In [226]:
print("Before:", model_data_clean.shape)
print("After:", model_data_clean_nd.shape)

Before: (75441, 15)
After: (75059, 15)

In [227]:
print("Before:", model_data_clean.shape)

model_data_clean_nd = model_data_clean.drop_duplicates()

print("After:", model_data_clean_nd.shape)

Before: (75441, 15)
After: (75059, 15)

In [208]:
model_data_clean_nd.duplicated().sum()

np.int64(0)

In [209]:
model_data_clean_nd.info()

<class 'pandas.core.frame.DataFrame'>
Index: 75059 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   country                     75059 non-null  object
 1   industry                    75059 non-null  object
 2   education_level             75059 non-null  object
 3   job_role                    75059 non-null  object
 4   years_experience            75059 non-null  float64
 5   salary_usd                  75059 non-null  float64
 6   company_size                75059 non-null  object
 7   remote_work                 75059 non-null  object
 8   ai_adoption_level           75059 non-null  float64
 9   ai_literacy_score           75059 non-null  float64
 10  training_hours              75059 non-null  float64
 11  reskilling_completed        75059 non-null  object
 12  automation_probability      75059 non-null  float64
 13  layoff_probability          75059 non-null  float64
 14  employment_status_after_ai  75059 non-null  object
dtypes: float64(7), object(8)
memory usage: 9.2+ MB

In [214]:
model_data_clean_nd.dtypes

country                        object
industry                       object
education_level                object
job_role                       object
years_experience              float64
salary_usd                    float64
company_size                   object
remote_work                    object
ai_adoption_level             float64
ai_literacy_score             float64
training_hours                float64
reskilling_completed           object
automation_probability        float64
layoff_probability            float64
employment_status_after_ai     object
dtype: object

In [215]:
for col in [
    "country",
    "industry",
    "education_level",
    "job_role",
    "company_size",
    "remote_work",
    "reskilling_completed",
    "employment_status_after_ai"
]:
    print("\n", col)
    print(model_data_clean_nd[col].unique())

 country
['Bangladesh' 'Denmark' 'Nigeria' 'Vietnam' 'Mexico' 'Australia'
 'Pakistan' 'Brazil' 'Portugal' 'Indonesia' 'Israel' 'Germany' 'India'
 'Singapore' 'Switzerland' 'Ghana' 'South Africa' 'UK' 'China' 'USA'
 'Philippines' 'Malaysia' 'Spain' 'Belgium' 'Italy' 'Argentina'
 'Saudi Arabia' 'Ireland' 'Turkey' 'UAE' 'Colombia' 'Thailand' 'Chile'
 'Romania' 'Norway' 'Poland' 'Canada' 'Egypt' 'France' 'Japan' 'Greece'
 'Morocco' 'Kenya' 'Netherlands' 'New Zealand' 'Peru' 'South Korea'
 'Finland' 'Hungary' 'Sweden' 'Czech Republic' 'Austria']

 industry
['Energy' 'Transportation' 'IT' 'Manufacturing' 'Retail' 'Agriculture'
 'Legal' 'Government' 'Healthcare' 'Hospitality' 'Finance' 'Education'
 'Construction' 'Media' 'Telecommunications']

 education_level
['Bachelor' 'High School' 'Master' 'Diploma' 'PhD']

 job_role
['Energy Auditor' 'Aviation Mechanic' 'DevOps Engineer'
 'Production Supervisor' 'Inventory Manager' 'Quality Control Inspector'
 'Renewable Energy Consultant' 'Farm Equipment Operator' 'Soil Scientist'
 'Judge' 'Civil Servant' 'HSE Officer' 'Product Manager'
 'Production Planner' 'Optometrist' 'Defense Analyst' 'Legal Assistant'
 'Chef' 'Finance Manager' 'Physical Therapist' 'Teaching Assistant'
 'Immigration Officer' 'Horticulturist' 'Retail Buyer'
 'IT Project Manager' 'Tour Guide' 'Government Auditor'
 'Site Reliability Engineer' 'Event Planner' 'Election Officer'
 'Crane Operator' 'Anesthesiologist' 'Manufacturing Technician'
 'Solutions Architect' 'Surveyor' 'Process Engineer'
 'Wind Turbine Technician' 'Resort Manager' 'Video Editor'
 'Law Firm Partner' 'Graphic Designer' 'Front Desk Agent' 'Tutor'
 'Restaurant Manager' 'Auditor' 'Registered Nurse' 'Truck Driver'
 'Retail Operations Manager' 'Education Administrator' 'Editor'
 'Architect' 'Petroleum Engineer' 'Administrative Assistant'
 'Packaging Operator' 'Livestock Manager' 'Logistics Coordinator'
 'Content Writer' 'Personal Shopper' 'Legal Secretary'
 'Full Stack Developer' 'Budget Officer' 'Floor Supervisor'
 'Public Administrator' 'Librarian' 'Concierge' 'Media Planner'
 'Regulatory Officer' 'Diplomat' 'Site Supervisor'
 'Online Course Instructor' 'Environmental Engineer'
 'Occupational Therapist' 'Investment Banker' 'Bank Teller'
 'VoIP Engineer' 'Tax Officer' 'Curriculum Developer'
 'Clinical Researcher' 'Civil Engineer' 'Technical Writer'
 'Public Relations Officer' 'Public Health Officer' 'Shipping Coordinator'
 'Loss Prevention Officer' 'Digital Marketing Manager'
 'Public Relations Specialist' 'Veterinarian' 'Spa Manager'
 'Healthcare Administrator' 'Early Childhood Educator' 'Data Scientist'
 'Plumber' 'Producer' 'Energy Policy Analyst' 'Systems Engineer'
 'Hospital Manager' 'Maritime Officer' 'Mobile App Developer' 'Bookkeeper'
 'Home Health Aide' 'Port Operations Manager' 'Budget Analyst'
 'CNC Operator' 'Social Media Manager' 'School Counselor' 'Dentist'
 'Field Engineer' 'Pricing Analyst' 'Education Policy Analyst'
 'Medical Lab Technician' 'Equity Research Analyst' 'Spectrum Analyst'
 'Roofer' 'Logistics Manager' 'Field Technician' 'Infrastructure Engineer'
 'Marketing Specialist' 'Business Analyst'
 'Customer Service Representative' 'Agronomist' 'Department Manager'
 'Academic Advisor' 'Freight Broker' 'Crop Consultant'
 'Fiber Optic Technician' 'News Anchor' 'Rural Extension Officer'
 'Utility Manager' 'Radiologist' 'Travel Agent' 'Greenhouse Manager'
 'Animator' 'Policy Analyst' 'Patent Attorney' 'Telecom Project Manager'
 'Database Administrator' 'Customs Officer' 'Electrical Engineer'
 'Maintenance Technician' 'Waiter/Waitress' 'Cloud Architect'
 'Financial Analyst' 'Quality Assurance Manager' 'Electrician'
 'Pharmacist' 'Agribusiness Manager' 'Welder' 'Special Education Teacher'
 'Banquet Coordinator' 'Power Plant Operator' 'IT Support Specialist'
 'Telecom Sales Executive' 'Vocational Trainer' 'Pipeline Engineer'
 'Lawyer' 'Retail District Manager' 'Accountant' 'Copywriter'
 'Construction Manager' 'Legal Consultant' 'Service Delivery Manager'
 'Insurance Underwriter' 'Sustainability Manager' 'Corporate Counsel'
 'Regulatory Affairs Specialist' 'Machine Learning Engineer'
 'Film Director' 'Legal Analyst' 'Lecturer' 'Dean' 'Legislative Assistant'
 'Hospitality Consultant' 'Financial Advisor' 'Network Engineer' 'Teacher'
 'Urban Planner' 'Housekeeping Supervisor' 'Actuary'
 'Guest Services Manager' 'HVAC Technician' 'Telecom Analyst'
 'Delivery Driver' 'Structural Engineer' 'Sales Associate'
 'Construction Estimator' 'Supply Chain Coordinator' 'Social Worker'
 'Risk Manager' 'Systems Administrator' 'E-commerce Manager'
 'Machine Operator' 'Loan Officer' 'Education Consultant' 'Store Manager'
 'Cybersecurity Analyst' 'Instructional Designer' 'Nuclear Engineer'
 'Research Assistant' 'QA Engineer' 'Assembly Line Worker'
 'Medical Assistant' 'Carpenter' 'Paralegal' 'General Physician'
 'Catering Manager' 'Transit Operations Manager' 'Energy Trader'
 'Contract Specialist' 'Communications Manager' 'Psychiatrist' 'Notary'
 'Retail Marketing Specialist' 'Cruise Staff' 'Statistician'
 'Software Engineer' 'Train Conductor' 'Forestry Technician'
 'Compliance Analyst' 'Mason' 'Tool and Die Maker' 'Farm Laborer'
 'Safety Inspector' 'Cashier' 'Solar Technician' 'Building Inspector'
 'Geologist' 'Bus Driver' 'School Principal' 'Surgeon' 'Portfolio Manager'
 'Food and Beverage Manager' 'Prosecutor' 'Network Operations Manager'
 'Legal Researcher' 'Journalist' 'Hotel Manager' 'Nutritionist'
 'Compliance Officer' 'Tax Consultant' 'Food Scientist' 'UI/UX Designer'
 'Public Defender' 'Dairy Farmer' 'Construction Laborer'
 'Project Engineer' 'Irrigation Technician' 'Professor'
 'Visual Merchandiser' 'Fleet Manager' 'Drilling Engineer'
 'Veterinary Technician' 'Satellite Communications Engineer'
 'Brand Strategist' 'Safety Officer' 'Photographer' 'Sound Engineer'
 'Stock Clerk' 'Grid Operator' 'Sommelier' 'Paramedic' 'Court Clerk'
 'Customs Inspector' 'Dispatcher' 'Broadcast Technician' 'Farm Manager'
 'Wireless Engineer' 'Pesticide Applicator' 'Agricultural Inspector'
 'Supply Planner' 'Telecom Consultant' 'Warehouse Manager'
 'Agricultural Engineer' 'Robotics Technician' 'Merchandise Planner'
 'Litigation Support Specialist' 'Industrial Engineer' 'Plant Manager'
 'Heavy Equipment Operator' 'Telecom Billing Analyst' 'Mediator'
 'Hedge Fund Analyst' 'Energy Analyst' 'Warehouse Associate'
 'Network Architect' 'Agricultural Sales Representative'
 'Transportation Planner' 'Treasury Analyst' 'Bartender' 'Credit Analyst'
 'Air Traffic Controller' 'Municipal Manager' 'Supply Chain Analyst'
 'RF Engineer' 'Telecom Technician' 'Fabrication Specialist' 'Courier'
 'Customer Support Engineer' 'Pilot']

 company_size
['Medium' 'Small' 'Large' 'Enterprise']

 remote_work
['No' 'Yes']

 reskilling_completed
['No' 'Yes']

 employment_status_after_ai
['Employed' 'Reskilled' 'Unemployed' 'Career Change']

In [216]:
model_data_clean_nd["ai_adoption_level"].unique()

array([ 90.06,  81.53, 100.  , ...,  32.05,  23.87,  16.74], shape=(8260,))

In [217]:
categorical_features = [
    "country",
    "industry",
    "education_level",
    "job_role",
    "company_size",
    "remote_work",
    "reskilling_completed"
]

In [218]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

encoded_array = encoder.fit_transform(
    model_data_clean_nd[categorical_features]
)

In [219]:
encoded_df = pd.DataFrame(
    encoded_array,
    columns=encoder.get_feature_names_out(categorical_features),
    index=model_data_clean_nd.index
)

In [221]:
model_data_clean_nd = model_data_clean_nd.drop(
    columns=categorical_features
)

In [222]:
model_data_clean_nd = pd.concat(
    [
        model_data_clean_nd,
        encoded_df
    ],
    axis=1
)

In [223]:
model_data_clean_nd.shape

(75059, 386)

In [224]:
model_data_clean_nd.head()

,years_experience,salary_usd,ai_adoption_level,ai_literacy_score,training_hours,automation_probability,layoff_probability,employment_status_after_ai,country_Argentina,country_Australia,...,job_role_Wind Turbine Technician,job_role_Wireless Engineer,company_size_Enterprise,company_size_Large,company_size_Medium,company_size_Small,remote_work_No,remote_work_Yes,reskilling_completed_No,reskilling_completed_Yes
0,7.0,14288.80,90.06,52.64,136.0,0.4382,0.1362,Employed,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,13.0,92290.01,81.53,47.79,55.5,0.4848,0.2122,Employed,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
2,34.0,12359.08,100.00,3.49,110.8,0.4564,0.1431,Employed,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
3,21.0,15811.44,97.83,44.29,109.7,0.6871,0.2724,Employed,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
4,13.0,9951.72,74.58,47.25,71.3,0.3714,0.1333,Employed,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0

In [228]:
print("After:", model_data_clean_nd.shape)

After: (75059, 15)

In [230]:
X = model_data_clean_nd.drop(columns=["employment_status_after_ai"])

y = model_data_clean_nd["employment_status_after_ai"]

In [231]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [232]:
numeric_features = [
    "years_experience",
    "salary_usd",
    "ai_adoption_level",
    "ai_literacy_score",
    "training_hours",
    "automation_probability",
    "layoff_probability"
]

categorical_features = [
    "country",
    "industry",
    "education_level",
    "job_role",
    "company_size",
    "remote_work",
    "reskilling_completed"
]

In [234]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        ("num", "passthrough", numeric_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

In [235]:
X_train_encoded = preprocessor.fit_transform(X_train)

In [236]:
X_test_encoded = preprocessor.transform(X_test)

In [237]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)

rf.fit(X_train_encoded, y_train)

RandomForestClassifier(random_state=42)

In [238]:
y_pred_rf = rf.predict(X_test_encoded)

In [240]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_rf))

               precision    recall  f1-score   support

Career Change       0.43      0.03      0.06       561
     Employed       0.88      1.00      0.94     13114
    Reskilled       0.47      0.01      0.01      1134
   Unemployed       0.43      0.33      0.37       203

     accuracy                           0.88     15012
    macro avg       0.55      0.34      0.35     15012
 weighted avg       0.83      0.88      0.83     15012

In [241]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    random_state=42,
    eval_metric="mlogloss"
)

In [243]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

In [244]:
xgb.fit(X_train_encoded, y_train_encoded)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [245]:
y_pred_xgb = xgb.predict(X_test_encoded)

In [247]:
y_pred_xgb = label_encoder.inverse_transform(y_pred_xgb)

In [249]:
from sklearn.metrics import accuracy_score, classification_report, f1_score

print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("Macro F1:", f1_score(y_test, y_pred_xgb, average="macro"))
print(classification_report(y_test, y_pred_xgb))

Accuracy: 0.8784972022382095
Macro F1: 0.3822104835760989
               precision    recall  f1-score   support

Career Change       0.26      0.04      0.07       561
     Employed       0.89      0.99      0.94     13114
    Reskilled       0.40      0.01      0.02      1134
   Unemployed       0.42      0.61      0.50       203

     accuracy                           0.88     15012
    macro avg       0.49      0.41      0.38     15012
 weighted avg       0.82      0.88      0.83     15012

In [251]:
import pandas as pd

df1 = pd.read_csv("../data/ai_job_impact_dataset.csv")

In [252]:
top_features = [
    "layoff_probability",
    "automation_probability",
    "mental_stress_score",
    "job_satisfaction",
    "training_hours",
    "ai_literacy_score",
    "innovation_score",
    "digital_skill_score",
    "productivity_score",
    "salary_usd",
    "promotion_probability",
    "annual_performance_rating",
    "hours_worked_per_week",
    "ai_adoption_level",
    "age",
    "years_experience"
]

target = "employment_status_after_ai"

In [253]:
model_data_top16 = df1[
    top_features + [target]
].copy()

In [254]:
model_data_top16.head()

,layoff_probability,automation_probability,mental_stress_score,job_satisfaction,training_hours,ai_literacy_score,innovation_score,digital_skill_score,productivity_score,salary_usd,promotion_probability,annual_performance_rating,hours_worked_per_week,ai_adoption_level,age,years_experience,employment_status_after_ai
0,0.1362,0.4382,23.29,8.01,136.0,52.64,46.19,39.60,64.25,14288.80,0.5516,4.16,37.7,90.06,36.0,7.0,Employed
1,0.2122,0.4848,19.45,8.00,55.5,47.79,59.25,38.48,46.15,92290.01,0.4824,3.65,41.6,81.53,58.0,13.0,Employed
2,0.1431,0.4564,47.87,6.11,110.8,3.49,16.69,7.28,38.16,12359.08,0.3561,3.42,42.3,100.00,59.0,34.0,Employed
3,0.2724,0.6871,38.92,5.64,109.7,44.29,39.84,40.89,76.66,15811.44,0.3547,3.77,40.0,97.83,54.0,21.0,Employed
4,0.1333,0.3714,27.33,9.68,71.3,47.25,47.53,39.41,64.97,9951.72,0.4796,3.79,31.3,74.58,54.0,13.0,Employed

In [255]:
model_data_top16.shape

(100000, 17)

In [256]:
model_data_top16.isnull().sum()

layoff_probability            1964
automation_probability        1958
mental_stress_score           2010
job_satisfaction              1948
training_hours                1932
ai_literacy_score             2011
innovation_score              2001
digital_skill_score           1894
productivity_score            2035
salary_usd                    2035
promotion_probability         1975
annual_performance_rating     1941
hours_worked_per_week         2036
ai_adoption_level             2002
age                           2027
years_experience              2023
employment_status_after_ai    2007
dtype: int64

In [257]:
model_data_top16 = model_data_top16.dropna()

In [258]:
model_data_top16.isnull().sum()

layoff_probability            0
automation_probability        0
mental_stress_score           0
job_satisfaction              0
training_hours                0
ai_literacy_score             0
innovation_score              0
digital_skill_score           0
productivity_score            0
salary_usd                    0
promotion_probability         0
annual_performance_rating     0
hours_worked_per_week         0
ai_adoption_level             0
age                           0
years_experience              0
employment_status_after_ai    0
dtype: int64

In [259]:
model_data_top16.duplicated().sum()

np.int64(346)

In [260]:
model_data_top16 = model_data_top16.drop_duplicates()

In [261]:
print(model_data_top16.shape)

print(model_data_top16.isnull().sum().sum())

print(model_data_top16.duplicated().sum())

(70828, 17)
0
0

In [367]:
X = model_data_top16.drop(
    columns=["employment_status_after_ai"]
)

y = model_data_top16["employment_status_after_ai"]

In [368]:
print(X.shape)
print(y.shape)

(70828, 16)
(70828,)

In [369]:
y.value_counts()

employment_status_after_ai
Employed         61822
Reskilled         5344
Career Change     2691
Unemployed         971
Name: count, dtype: int64

In [370]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [371]:
print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (56662, 16)
Testing data: (14166, 16)

In [372]:
print(y_train.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

employment_status_after_ai
Employed         0.872842
Reskilled        0.075447
Career Change    0.037997
Unemployed       0.013713
Name: proportion, dtype: float64
employment_status_after_ai
Employed         0.872865
Reskilled        0.075462
Career Change    0.037978
Unemployed       0.013695
Name: proportion, dtype: float64

In [375]:
from sklearn.ensemble import RandomForestClassifier

rf_top16 = RandomForestClassifier(
    random_state=42
)

In [376]:
rf_top16.fit(
    X_train,
    y_train
)

RandomForestClassifier(random_state=42)

In [270]:
y_pred = rf_top16.predict(X_test)

In [271]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(
    y_test,
    y_pred
)

print("Accuracy:", accuracy)

Accuracy: 0.8778766059579274

In [272]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        y_pred
    )
)

               precision    recall  f1-score   support

Career Change       0.26      0.04      0.07       538
     Employed       0.89      0.99      0.94     12365
    Reskilled       0.00      0.00      0.00      1069
   Unemployed       0.44      0.73      0.55       194

     accuracy                           0.88     14166
    macro avg       0.40      0.44      0.39     14166
 weighted avg       0.79      0.88      0.83     14166

/Users/syedafnan/First Semester/Statistics & ML/impact-ai-jobs-impact-ml/ml_venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/syedafnan/First Semester/Statistics & ML/impact-ai-jobs-impact-ml/ml_venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/syedafnan/First Semester/Statistics & ML/impact-ai-jobs-impact-ml/ml_venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [377]:
rf_balanced = RandomForestClassifier(
    random_state=42,
    class_weight="balanced"
)

In [378]:
rf_balanced.fit(
    X_train,
    y_train
)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [379]:
y_pred = rf_balanced.predict(X_test)

In [381]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        y_pred
    )
)

               precision    recall  f1-score   support

Career Change       0.20      0.14      0.16       538
     Employed       0.91      0.95      0.93     12365
    Reskilled       0.16      0.09      0.11      1069
   Unemployed       0.42      0.68      0.52       194

     accuracy                           0.85     14166
    macro avg       0.42      0.46      0.43     14166
 weighted avg       0.82      0.85      0.83     14166

In [382]:
from sklearn.metrics import (
    classification_report,
    f1_score,
    accuracy_score,
    precision_score,
    recall_score
)

accuracy = accuracy_score(y_test, y_pred)

macro_precision = precision_score(
    y_test,
    y_pred,
    average="macro"
)

macro_recall = recall_score(
    y_test,
    y_pred,
    average="macro"
)

macro_f1 = f1_score(
    y_test,
    y_pred,
    average="macro"
)

print("Accuracy:", accuracy)
print("Macro Precision:", macro_precision)
print("Macro Recall:", macro_recall)
print("Macro F1:", macro_f1)

print(classification_report(y_test, y_pred))

Accuracy: 0.8464633629817874
Macro Precision: 0.42216435315828643
Macro Recall: 0.46093632161183345
Macro F1: 0.4299519158722142
               precision    recall  f1-score   support

Career Change       0.20      0.14      0.16       538
     Employed       0.91      0.95      0.93     12365
    Reskilled       0.16      0.09      0.11      1069
   Unemployed       0.42      0.68      0.52       194

     accuracy                           0.85     14166
    macro avg       0.42      0.46      0.43     14166
 weighted avg       0.82      0.85      0.83     14166

In [383]:
run_id = "2baa224b743a4795a6a3d090a8c7b6ec"

with mlflow.start_run(run_id=run_id):

    mlflow.log_metric("macro_precision", macro_precision)
    mlflow.log_metric("macro_recall", macro_recall)

#######################################################################################################################

In [330]:
print(rf_balanced)
print(X_test.shape)
print(y_test.shape)

RandomForestClassifier(class_weight='balanced', random_state=42)
(14166, 16)
(14166,)

In [ ]:
import mlflow
import mlflow.sklearn
from sklearn.metrics import accuracy_score, f1_score


with mlflow.start_run(run_name="RandomForest_Balanced"):

    y_pred = rf_balanced.predict(X_test)

    accuracy = accuracy_score(
        y_test,
        y_pred
    )

    macro_f1 = f1_score(
        y_test,
        y_pred,
        average="macro"
    )

    mlflow.log_metric(
        "accuracy",
        accuracy
    )

    mlflow.log_metric(
        "macro_f1",
        macro_f1
    )

    mlflow.log_params(
        rf_balanced.get_params()
    )

    mlflow.sklearn.log_model(
        rf_balanced,
        "model"
    )

2026/07/27 14:28:28 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

In [318]:
mlflow.search_runs()

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.accuracy,metrics.macro_f1,params.warm_start,params.min_samples_leaf,...,params.min_weight_fraction_leaf,params.min_samples_split,params.class_weight,params.n_estimators,params.min_impurity_decrease,params.max_features,tags.mlflow.runName,tags.mlflow.source.name,tags.mlflow.source.type,tags.mlflow.user
0,2baa224b743a4795a6a3d090a8c7b6ec,1,FINISHED,/Users/syedafnan/First Semester/Statistics & M...,2026-07-27 12:28:27.830000+00:00,2026-07-27 12:28:31.692000+00:00,0.846463,0.429952,False,1,...,0.0,2,balanced,100,0.0,sqrt,RandomForest_Balanced,exploration.ipynb,NOTEBOOK,syedafnan

In [325]:
import mlflow

mlflow.set_tracking_uri(
    "sqlite:///mlflow.db"
)

print(mlflow.get_tracking_uri())

sqlite:///mlflow.db

In [326]:
mlflow.set_experiment(
    "AI_Job_Impact_Classification"
)

2026/07/27 14:22:14 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/07/27 14:22:14 INFO mlflow.store.db.utils: Updating database tables
2026/07/27 14:22:14 INFO mlflow.tracking.fluent: Experiment with name 'AI_Job_Impact_Classification' does not exist. Creating a new experiment.

<Experiment: artifact_location=('/Users/syedafnan/First Semester/Statistics & '
 'ML/impact-ai-jobs-impact-ml/notebooks/mlruns/1'), creation_time=1785154934548, effective_trace_archival_retention=None, experiment_id='1', last_update_time=1785154934548, lifecycle_stage='active', name='AI_Job_Impact_Classification', tags={}, trace_location=None, workspace='default'>

In [328]:
experiments = mlflow.search_experiments()

for exp in experiments:
    print(exp.name, exp.experiment_id)

AI_Job_Impact_Classification 1
Default 0

In [329]:
import mlflow

mlflow.set_tracking_uri("sqlite:///mlflow.db")

mlflow.set_experiment(
    "AI_Job_Impact_Classification"
)

<Experiment: artifact_location=('/Users/syedafnan/First Semester/Statistics & '
 'ML/impact-ai-jobs-impact-ml/notebooks/mlruns/1'), creation_time=1785154934548, effective_trace_archival_retention=None, experiment_id='1', last_update_time=1785154934548, lifecycle_stage='active', name='AI_Job_Impact_Classification', tags={}, trace_location=None, workspace='default'>

In [334]:
runs = mlflow.search_runs(
    experiment_names=["AI_Job_Impact_Classification"]
)

runs[["run_id", "tags.mlflow.runName"]]

                             run_id    tags.mlflow.runName
0  2baa224b743a4795a6a3d090a8c7b6ec  RandomForest_Balanced

In [336]:
mlflow.register_model(
    model_uri="runs:/2baa224b743a4795a6a3d090a8c7b6ec/model",
    name="AI_Job_Impact_Model"
)

Registered model 'AI_Job_Impact_Model' already exists. Creating a new version of this model...
2026/07/27 14:47:37 WARNING mlflow.tracking._model_registry.fluent: Run with id 2baa224b743a4795a6a3d090a8c7b6ec has no artifacts at artifact path 'model', registering model based on models:/m-c79e85cf07c241979351b806aad0b7b4 instead
Created version '1' of model 'AI_Job_Impact_Model'.

<ModelVersion: aliases=[], creation_timestamp=1785156457926, current_stage='None', deployment_job_state=None, description=None, last_updated_timestamp=1785156457926, metrics=None, model_id=None, name='AI_Job_Impact_Model', params=None, run_id='2baa224b743a4795a6a3d090a8c7b6ec', run_link=None, source='models:/m-c79e85cf07c241979351b806aad0b7b4', status='READY', status_message=None, tags={}, user_id=None, version=1, workspace='default'>

In [337]:
from mlflow.tracking import MlflowClient

client = MlflowClient()

registered_models = client.search_registered_models()

for model in registered_models:
    print(model.name)

AI_Job_Impact_Model

In [338]:
model = client.get_registered_model("AI_Job_Impact_Model")

for version in model.latest_versions:
    print(
        "Version:",
        version.version,
        "Stage:",
        version.current_stage,
        "Run ID:",
        version.run_id
    )

Version: 1 Stage: None Run ID: 2baa224b743a4795a6a3d090a8c7b6ec

In [339]:
model_data_clean_nd.dtypes

country                        object
industry                       object
education_level                object
job_role                       object
years_experience              float64
salary_usd                    float64
company_size                   object
remote_work                    object
ai_adoption_level             float64
ai_literacy_score             float64
training_hours                float64
reskilling_completed           object
automation_probability        float64
layoff_probability            float64
employment_status_after_ai     object
dtype: object

In [394]:
X = model_data_top16.drop(
    columns=["employment_status_after_ai"]
)

y = model_data_top16["employment_status_after_ai"]

In [395]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [344]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    class_weight="balanced",
    random_state=42
)

In [345]:
param_grid = {
    "n_estimators": [200, 500],
    "max_depth": [10, 20, None],
    "min_samples_leaf": [1, 2]
}

In [346]:
from sklearn.model_selection import GridSearchCV

grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    scoring="f1_macro",
    cv=5,
    n_jobs=-1,
    verbose=2
)

In [347]:
grid_search.fit(
    X_train,
    y_train
)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV] END .max_depth=10, min_samples_leaf=1, n_estimators=200; total time=  11.8s
[CV] END .max_depth=10, min_samples_leaf=1, n_estimators=200; total time=  11.7s
[CV] END .max_depth=10, min_samples_leaf=1, n_estimators=200; total time=  11.8s
[CV] END .max_depth=10, min_samples_leaf=1, n_estimators=200; total time=  11.8s
[CV] END .max_depth=10, min_samples_leaf=1, n_estimators=200; total time=  11.9s
[CV] END .max_depth=10, min_samples_leaf=2, n_estimators=200; total time=  12.2s
[CV] END .max_depth=10, min_samples_leaf=2, n_estimators=200; total time=  12.1s
[CV] END .max_depth=10, min_samples_leaf=2, n_estimators=200; total time=  12.1s
[CV] END .max_depth=10, min_samples_leaf=2, n_estimators=200; total time=  12.1s
[CV] END .max_depth=10, min_samples_leaf=2, n_estimators=200; total time=  12.1s
[CV] END .max_depth=10, min_samples_leaf=1, n_estimators=500; total time=  29.7s
[CV] END .max_depth=10, min_samples_leaf=1, n_estimators=500; total time=  29.8s
[CV] END .max_depth=10, min_samples_leaf=1, n_estimators=500; total time=  29.8s
[CV] END .max_depth=10, min_samples_leaf=1, n_estimators=500; total time=  29.9s
[CV] END .max_depth=10, min_samples_leaf=1, n_estimators=500; total time=  30.1s
[CV] END .max_depth=20, min_samples_leaf=1, n_estimators=200; total time=  17.7s
[CV] END .max_depth=20, min_samples_leaf=1, n_estimators=200; total time=  17.8s
[CV] END .max_depth=20, min_samples_leaf=1, n_estimators=200; total time=  17.9s
[CV] END .max_depth=20, min_samples_leaf=1, n_estimators=200; total time=  17.8s
[CV] END .max_depth=20, min_samples_leaf=1, n_estimators=200; total time=  17.9s
[CV] END .max_depth=10, min_samples_leaf=2, n_estimators=500; total time=  30.5s
[CV] END .max_depth=10, min_samples_leaf=2, n_estimators=500; total time=  30.7s
[CV] END .max_depth=10, min_samples_leaf=2, n_estimators=500; total time=  30.6s
[CV] END .max_depth=10, min_samples_leaf=2, n_estimators=500; total time=  30.5s
[CV] END .max_depth=10, min_samples_leaf=2, n_estimators=500; total time=  30.6s
[CV] END .max_depth=20, min_samples_leaf=2, n_estimators=200; total time=  17.7s
[CV] END .max_depth=20, min_samples_leaf=2, n_estimators=200; total time=  17.9s
[CV] END .max_depth=20, min_samples_leaf=2, n_estimators=200; total time=  17.8s
[CV] END .max_depth=20, min_samples_leaf=2, n_estimators=200; total time=  17.9s
[CV] END .max_depth=20, min_samples_leaf=2, n_estimators=200; total time=  17.8s
[CV] END .max_depth=20, min_samples_leaf=1, n_estimators=500; total time=  45.4s
[CV] END .max_depth=20, min_samples_leaf=1, n_estimators=500; total time=  45.8s
[CV] END .max_depth=20, min_samples_leaf=1, n_estimators=500; total time=  45.7s
[CV] END .max_depth=20, min_samples_leaf=1, n_estimators=500; total time=  46.1s
[CV] END .max_depth=20, min_samples_leaf=1, n_estimators=500; total time=  45.8s
[CV] END max_depth=None, min_samples_leaf=1, n_estimators=200; total time=  20.0s
[CV] END max_depth=None, min_samples_leaf=1, n_estimators=200; total time=  19.9s
[CV] END max_depth=None, min_samples_leaf=1, n_estimators=200; total time=  19.9s
[CV] END max_depth=None, min_samples_leaf=1, n_estimators=200; total time=  19.8s
[CV] END max_depth=None, min_samples_leaf=1, n_estimators=200; total time=  19.8s
[CV] END .max_depth=20, min_samples_leaf=2, n_estimators=500; total time=  45.3s
[CV] END .max_depth=20, min_samples_leaf=2, n_estimators=500; total time=  45.7s
[CV] END .max_depth=20, min_samples_leaf=2, n_estimators=500; total time=  45.6s
[CV] END .max_depth=20, min_samples_leaf=2, n_estimators=500; total time=  45.6s
[CV] END .max_depth=20, min_samples_leaf=2, n_estimators=500; total time=  45.8s
[CV] END max_depth=None, min_samples_leaf=2, n_estimators=200; total time=  19.6s
[CV] END max_depth=None, min_samples_leaf=2, n_estimators=200; total time=  19.9s
[CV] END max_depth=None, min_samples_leaf=2, n_estimators=200; total time=  20.1s
[CV] END max_depth=None, min_samples_leaf=2, n_estimators=200; total time=  19.8s
[CV] END max_depth=None, min_samples_leaf=2, n_estimators=200; total time=  19.8s
[CV] END max_depth=None, min_samples_leaf=1, n_estimators=500; total time=  50.8s
[CV] END max_depth=None, min_samples_leaf=1, n_estimators=500; total time=  51.0s
[CV] END max_depth=None, min_samples_leaf=1, n_estimators=500; total time=  51.5s
[CV] END max_depth=None, min_samples_leaf=1, n_estimators=500; total time=  51.5s
[CV] END max_depth=None, min_samples_leaf=1, n_estimators=500; total time=  51.3s
[CV] END max_depth=None, min_samples_leaf=2, n_estimators=500; total time=  45.4s
[CV] END max_depth=None, min_samples_leaf=2, n_estimators=500; total time=  45.7s
[CV] END max_depth=None, min_samples_leaf=2, n_estimators=500; total time=  46.3s
[CV] END max_depth=None, min_samples_leaf=2, n_estimators=500; total time=  45.8s
[CV] END max_depth=None, min_samples_leaf=2, n_estimators=500; total time=  46.2s

GridSearchCV(cv=5,
             estimator=RandomForestClassifier(class_weight='balanced',
                                              random_state=42),
             n_jobs=-1,
             param_grid={'max_depth': [10, 20, None],
                         'min_samples_leaf': [1, 2],
                         'n_estimators': [200, 500]},
             scoring='f1_macro', verbose=2)

In [356]:
grid_search.best_params_

{'max_depth': 20, 'min_samples_leaf': 2, 'n_estimators': 500}

In [357]:
grid_search.best_score_

np.float64(0.4513423380034651)

In [351]:
best_rf = grid_search.best_estimator_

In [352]:
y_pred = best_rf.predict(X_test)

In [364]:
from sklearn.metrics import classification_report, f1_score, accuracy_score

accuracy = accuracy_score(y_test, y_pred)
macro_f1 = f1_score(y_test, y_pred, average="macro")

print("Accuracy:",
      accuracy)

print("Macro F1:",
      macro_f1)

print(classification_report(y_test, y_pred))

Accuracy: 0.7612593533813355
Macro F1: 0.4583817975393768
               precision    recall  f1-score   support

Career Change       0.13      0.36      0.20       538
     Employed       0.94      0.82      0.88     12365
    Reskilled       0.15      0.21      0.17      1069
   Unemployed       0.44      0.90      0.59       194

     accuracy                           0.76     14166
    macro avg       0.41      0.57      0.46     14166
 weighted avg       0.84      0.76      0.80     14166

Current ranking:

🥇 GridSearchCV RF

Macro F1: 0.46
Better minority class detection

🥈 Balanced RF

Macro F1: 0.43

🥉 Normal RF

Macro F1: 0.39

In [365]:
from sklearn.metrics import (
    classification_report,
    f1_score,
    accuracy_score,
    precision_score,
    recall_score
)

accuracy = accuracy_score(y_test, y_pred)

macro_precision = precision_score(
    y_test,
    y_pred,
    average="macro"
)

macro_recall = recall_score(
    y_test,
    y_pred,
    average="macro"
)

macro_f1 = f1_score(
    y_test,
    y_pred,
    average="macro"
)

print("Accuracy:", accuracy)
print("Macro Precision:", macro_precision)
print("Macro Recall:", macro_recall)
print("Macro F1:", macro_f1)

print(classification_report(y_test, y_pred))

Accuracy: 0.7612593533813355
Macro Precision: 0.414671433366126
Macro Recall: 0.5710657303108354
Macro F1: 0.4583817975393768
               precision    recall  f1-score   support

Career Change       0.13      0.36      0.20       538
     Employed       0.94      0.82      0.88     12365
    Reskilled       0.15      0.21      0.17      1069
   Unemployed       0.44      0.90      0.59       194

     accuracy                           0.76     14166
    macro avg       0.41      0.57      0.46     14166
 weighted avg       0.84      0.76      0.80     14166

In [360]:
import mlflow
import mlflow.sklearn

mlflow.set_experiment("AI_Job_Impact_Classification")

with mlflow.start_run(run_name="RandomForest_GridSearchCV"):

    # Log metrics
    mlflow.log_metric("accuracy", accuracy)
    mlflow.log_metric("macro_f1", macro_f1)

    # Log the best hyperparameters found by GridSearchCV
    mlflow.log_params(grid_search.best_params_)

    # Save the trained model
    mlflow.sklearn.log_model(best_rf, "model")

2026/07/27 15:18:20 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

In [361]:
runs = mlflow.search_runs(
    experiment_names=["AI_Job_Impact_Classification"]
)

runs[["run_id", "tags.mlflow.runName"]]

                             run_id        tags.mlflow.runName
0  3679e2a2999841e89a50966c4c24c632  RandomForest_GridSearchCV
1  2baa224b743a4795a6a3d090a8c7b6ec      RandomForest_Balanced

In [362]:
mlflow.register_model(
    model_uri="runs:/3679e2a2999841e89a50966c4c24c632/model",
    name="AI_Job_Impact_Model"
)

Registered model 'AI_Job_Impact_Model' already exists. Creating a new version of this model...
2026/07/27 15:19:32 WARNING mlflow.tracking._model_registry.fluent: Run with id 3679e2a2999841e89a50966c4c24c632 has no artifacts at artifact path 'model', registering model based on models:/m-8f949c09fb4f4593bfc29e535fc62b73 instead
Created version '2' of model 'AI_Job_Impact_Model'.

<ModelVersion: aliases=[], creation_timestamp=1785158372417, current_stage='None', deployment_job_state=None, description=None, last_updated_timestamp=1785158372417, metrics=None, model_id=None, name='AI_Job_Impact_Model', params=None, run_id='3679e2a2999841e89a50966c4c24c632', run_link=None, source='models:/m-8f949c09fb4f4593bfc29e535fc62b73', status='READY', status_message=None, tags={}, user_id=None, version=2, workspace='default'>

In [363]:
runs = mlflow.search_runs(
    experiment_names=["AI_Job_Impact_Classification"]
)

runs

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.accuracy,metrics.macro_f1,params.n_estimators,params.max_depth,...,params.ccp_alpha,params.min_weight_fraction_leaf,params.min_samples_split,params.class_weight,params.min_impurity_decrease,params.max_features,tags.mlflow.runName,tags.mlflow.source.name,tags.mlflow.source.type,tags.mlflow.user
0,3679e2a2999841e89a50966c4c24c632,1,FINISHED,/Users/syedafnan/First Semester/Statistics & M...,2026-07-27 13:18:20.946000+00:00,2026-07-27 13:18:25.524000+00:00,0.761259,0.458382,500,20,...,None,None,None,None,None,None,RandomForest_GridSearchCV,exploration.ipynb,NOTEBOOK,syedafnan
1,2baa224b743a4795a6a3d090a8c7b6ec,1,FINISHED,/Users/syedafnan/First Semester/Statistics & M...,2026-07-27 12:28:27.830000+00:00,2026-07-27 12:28:31.692000+00:00,0.846463,0.429952,100,None,...,0.0,0.0,2,balanced,0.0,sqrt,RandomForest_Balanced,exploration.ipynb,NOTEBOOK,syedafnan

In [366]:
run_id = "3679e2a2999841e89a50966c4c24c632"

with mlflow.start_run(run_id=run_id):

    mlflow.log_metric("macro_precision", macro_precision)
    mlflow.log_metric("macro_recall", macro_recall)

In [ ]:
run_id = "2baa224b743a4795a6a3d090a8c7b6ec"

with mlflow.start_run(run_id=run_id):

    mlflow.log_metric("macro_precision", macro_precision)
    mlflow.log_metric("macro_recall", macro_recall)

In [384]:
from mlflow.tracking import MlflowClient

client = MlflowClient()

model = client.get_registered_model("AI_Job_Impact_Model")

for version in model.latest_versions:
    print(
        "Version:", version.version,
        "Run ID:", version.run_id
    )

Version: 2 Run ID: 3679e2a2999841e89a50966c4c24c632

In [385]:
client.set_model_version_tag(
    name="AI_Job_Impact_Model",
    version=1,
    key="role",
    value="champion"
)

In [386]:
client.set_model_version_tag(
    name="AI_Job_Impact_Model",
    version=2,
    key="role",
    value="challenger"
)

In [387]:
import mlflow.pyfunc

champion_model = mlflow.pyfunc.load_model(
    "models:/AI_Job_Impact_Model/1"
)

In [388]:
predictions = champion_model.predict(X_test)

print(predictions[:10])

['Employed' 'Reskilled' 'Employed' 'Employed' 'Employed' 'Employed'
 'Employed' 'Employed' 'Employed' 'Employed']

In [389]:
import mlflow.pyfunc

champion_model = mlflow.pyfunc.load_model(
    "models:/AI_Job_Impact_Model/2"
)

In [390]:
predictions = champion_model.predict(X_test)

print(predictions[:10])

['Employed' 'Career Change' 'Employed' 'Employed' 'Reskilled' 'Employed'
 'Employed' 'Employed' 'Employed' 'Employed']

In [391]:
best_rf = grid_search.best_estimator_

original_predictions = best_rf.predict(X_test)

(predictions == original_predictions).mean()

np.float64(1.0)

In [404]:
from sklearn.pipeline import Pipeline

final_pipeline = Pipeline([
    ("model", best_rf)
])

In [405]:
final_pipeline.fit(X_train, y_train)

Pipeline(steps=[('model',
                 RandomForestClassifier(class_weight='balanced', max_depth=20,
                                        min_samples_leaf=2, n_estimators=500,
                                        random_state=42))])

In [406]:
predictions = final_pipeline.predict(X_test)

print(predictions[:10])

['Employed' 'Career Change' 'Employed' 'Employed' 'Reskilled' 'Employed'
 'Employed' 'Employed' 'Employed' 'Employed']

In [408]:
with mlflow.start_run(run_name="RandomForest_GridSearchCV_pipeline"):

    mlflow.sklearn.log_model(
        final_pipeline,
        "model",
        registered_model_name="AI_Job_Impact_Model"
    )

2026/07/27 23:49:15 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
Registered model 'AI_Job_Impact_Model' already exists. Creating a new version of this model...
Created version '3' of model 'AI_Job_Impact_Model'.

In [409]:
import mlflow.pyfunc

champion_model = mlflow.pyfunc.load_model(
    "models:/AI_Job_Impact_Model/3"
)

In [410]:
predictions = champion_model.predict(X_test)

print(predictions[:10])

['Employed' 'Career Change' 'Employed' 'Employed' 'Reskilled' 'Employed'
 'Employed' 'Employed' 'Employed' 'Employed']

In [411]:
(best_rf.predict(X_test) == predictions).mean()

np.float64(1.0)

In [412]:
import mlflow

model_info = mlflow.models.get_model_info(
    "models:/AI_Job_Impact_Model/3"
)

print(model_info.signature)

None

In [413]:
from mlflow.models import infer_signature

# example input
input_example = X_train.iloc[:5]

# get predictions
output_example = final_pipeline.predict(input_example)

signature = infer_signature(
    input_example,
    output_example
)

print(signature)

inputs:
  ['layoff_probability': double (required), 'automation_probability': double (required), 'mental_stress_score': double (required), 'job_satisfaction': double (required), 'training_hours': double (required), 'ai_literacy_score': double (required), 'innovation_score': double (required), 'digital_skill_score': double (required), 'productivity_score': double (required), 'salary_usd': double (required), 'promotion_probability': double (required), 'annual_performance_rating': double (required), 'hours_worked_per_week': double (required), 'ai_adoption_level': double (required), 'age': double (required), 'years_experience': double (required)]
outputs:
  [Tensor('object', (-1,))]
params:
  None

In [414]:
with mlflow.start_run(run_name="RandomForest_GridSearchCV_pipeline_signature"):

    mlflow.sklearn.log_model(
        final_pipeline,
        "model",
        signature=signature,
        input_example=input_example,
        registered_model_name="AI_Job_Impact_Model"
    )

2026/07/27 23:55:04 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
Registered model 'AI_Job_Impact_Model' already exists. Creating a new version of this model...
Created version '4' of model 'AI_Job_Impact_Model'.

In [415]:
model_info = mlflow.models.get_model_info(
    "models:/AI_Job_Impact_Model/4"
)

print(model_info.signature)

inputs:
  ['layoff_probability': double (required), 'automation_probability': double (required), 'mental_stress_score': double (required), 'job_satisfaction': double (required), 'training_hours': double (required), 'ai_literacy_score': double (required), 'innovation_score': double (required), 'digital_skill_score': double (required), 'productivity_score': double (required), 'salary_usd': double (required), 'promotion_probability': double (required), 'annual_performance_rating': double (required), 'hours_worked_per_week': double (required), 'ai_adoption_level': double (required), 'age': double (required), 'years_experience': double (required)]
outputs:
  [Tensor('object', (-1,))]
params:
  None